### ISSUE TITLE
Evaluate what to do with build script in containers monorepo

### ISSUE THREAD

**Issue by maeve-fpf** [freedomofpress/containers#22]
We have a `build.py` here, but the Codefresh pipeline for this repo doesn't run it, and so has to have individual trigger configuration for each container that it will build.

I would like to improve or replace this script (also, have the interface for running it be `make` like most other repos) and make things flexible enough to be run by CI or locally.

For CI usage, it should be able to use the changed files that Codefresh detects to decide what to build, and expose the tag as something that Codefresh can `cf_export` to be used in the push step (right now that is part of the per-image config over in CF, and I hate the format it uses). Tags should look like `1.0-buster`, `2.0-alpine`, etc (`2020.06.30` style instead of `1.0` is fine if we don't want to have to think about it), not `master_1234abcd`. CF should push both to the tag extracted from metadata and `latest` (it can do this, might still need an opt-in to new pipeline features but that's simple).

**Comment by maeve-fpf** [comment]
I'm sort of leaning towards dumping this and going to one-repo-per-container. In my opinion the common parts of the process shouldn't be more than `docker build` and `docker push`. It would give us greater flexibility in configuring CI and setting access control on the repos themselves (private containers can be private). Throwing over to the discussion points column.

**Comment by echoesactiii** [comment]
One other concern I forgot to mention in infra sync on this: we use slack integrations on a lot of our stuff, and I don't know about everyone else, but I've come to rely on those. Setting those up for each and every new repo/container could be a headache to keep track of. It might be useful to come up with some process to make sure the new container repos get their slack integrations enabled.

**Comment by maeve-fpf** [comment]
At sync we discussed pros and cons here. Problems with individual repos:

- We have to set up each one. While our Terraform module for repos could stand to be improved to make this smoother, there are currently intractable problems like setting the default branch on creation (why is this not an account setting already) or subscribing to the repo in the GitHub Slack integration (how is there not an API for that? oof).
- We have to put a CI config in each one. This will probably be copy and paste.
- We have to find all the container-* repos in our org list.

Benefits:

- We can adjust the required PR review per repo, if our GitHub TF module's defaults aren't what we want. (This may lead to additional work resolving the pain points in using that module.)
- We can individually set read/write access, either by team or to make a container repo private entirely (we are currently doing this with gce-instance-culler so we have to either evaluate making that public or leave it split out in its own repo).
- We can tag in a meaningful way. I would really like container tags to be derived from repo tags with git describe. (I guess this boils down to "Maeve doesn't like working in monorepos".)

We brought up the possibility of having direct pushes to main in some repos, but I think I would rather go through review.

For the monorepo we can have one Codefresh pipeline with many triggers: this is pretty well supported (https://codefresh.io/docs/docs/configure-ci-cd-pipeline/triggers/git-triggers/#monorepo-support-modified-files), whereas on CircleCI you need a hack (https://medium.com/@reuvenharrison/using-circleci-with-monorepos-c04b03f9f39c) which is definitely not appealing. The trigger would be the same amount of YAML whether it keys off of repo name or modified path (it does not like there is a way to make either approach one generic trigger and parameterized on what was pushed), which would probably be copy and paste, also.

**Comment by maeve-fpf** [comment]
OK, to recap the current situation with regard to the build script itself: I made updates to the existing container triggers in https://github.com/freedomofpress/cf-pipelines/pull/43 and confirmed that `build.py` isn't used there at all. I don't see a use for it, or where it would fit in Codefresh (where "build" is a separate step, not something you drive by running a command), so I suggest we remove it.

At the moment, any pushes to the default branch in containers cause CircleCI to run what I think are intended to be tests on this script, but there aren't any, so it has nothing to do after installing dependencies.

I think https://github.com/freedomofpress/cf-pipelines/pull/43 is a good enough demonstration that we don't have to have some sort of One True Way w/r/t monorepos or not; trigger setup is mostly the same for either approach. So, we can put things in their own repo if it would be useful for them to be a submodule (https://github.com/freedomofpress/k8s-configs/pull/105), keep them that way if they're private (https://github.com/freedomofpress/container-gce-instance-culler/) or drop them in `containers` if they're so small that a repo would be silly (https://github.com/freedomofpress/containers/pull/25).
